Controllers/CapturadeOCController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using CodigosQRComprasCEDIS_2._0.Helpers;
using CodigosQRComprasCEDIS_2._0.Models;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Net;
using System.Text;
using iText.Html2pdf;

namespace CodigosQRComprasCEDIS_2._0.Controllers
{
  public class CapturadeOCController : Controller
  {
    public IActionResult IndexAsync()
    {
      ViewBag.vista = "capturaOC";
      //LdapHelper ldap = new LdapHelper();
      //List<EntryAD> groups = ldap.SearchForGroup("OC");
      //ViewBag.AD = groups;
      return View();
    }

    public IActionResult VisorCodigosQR()
    {
      ViewBag.vista = "visor";
      return View();
    }

    public async Task<IActionResult> Carrusel(String purchaseOrderNumber, String Company)
    {
      ViewBag.vista = "carrusel";
      ResultTransform result = await GetImagesPathsAsync(purchaseOrderNumber, "0", "N/A", null, 0, Company);
      ViewBag.images = result.data;
      GetConfigsData configs = new GetConfigsData();
      String config = configs.GetConfigurationData("Config").Result;
      if (config != "DESARROLLO")
      {
        ViewBag.rutaImg = "https://ayt-apps.eastus.cloudapp.azure.com/CodigosQR";
      }
      else
      {
        //ViewBag.rutaImg = "https://localhost:6061/";
        ViewBag.rutaImg = "https://ayt-apps.eastus.cloudapp.azure.com/CodigosQRTest";
      }
      return View();
    }

    [HttpPost]
    public async Task<JsonResult> GetDataOCAsync(String OC, String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      ResponseOrdenCompra oc = await capturadeOC.GetDataOC(OC);
      List<String[]> ocLine = await capturadeOC.GetDataOCLinea(OC);
      return Json(new { data = ocLine, dataocHead = (oc.value.Count > 0) ? oc.value[0] : null });
    }

    [HttpPost]
    public async Task<JsonResult> GetDataOCCodigosAsync(String OC, String ocRevision, String revision, String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      ResponseOrdenCompra oc = await capturadeOC.GetDataOC(OC);
      List<String[]> ocLine = await capturadeOC.GetDataOCLineaCodigos(OC, ocRevision, revision);
      return Json(new { data = ocLine, dataocHead = (oc.value.Count > 0) ? oc.value[0] : null });
    }

    [HttpPost]
    public async Task<JsonResult> SaveDataOCAsync(OrdenCompraHeader header, List<OrdenCompraLinea> lines, String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      JsonResult response = Json(await capturadeOC.SaveDataOC(header, lines, User.Identity.Name));
      return response;
    }

    [HttpPost]
    public async Task<ResultTransform> GetImagesPathsAsync(String purchaseOrderNumber, String lineNumber, String itemNumber, String oc, int revision, String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      ResultTransform result = await capturadeOC.GetImagesPaths(purchaseOrderNumber, lineNumber, itemNumber, oc, revision);
      return result;
    }

    public async Task<JsonResult> SaveImagesComentAsync(List<Data> DataLote, List<ComentImg> ComentImagen, DataOrd DataOrden, String Revision, String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      var Usuario = User.Identity.Name;
      var result = await capturadeOC.SaveImagesComent(DataLote, ComentImagen, DataOrden, Usuario, Revision);
      return Json(result);
    }

    public async Task<JsonResult> RemoveLoteComentAsync(DataLoteComent data, String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      var result = await capturadeOC.RemoveLoteComent(data);
      return Json(result);
    }

    public async Task<JsonResult> CargarDataOCVisorAsync(String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      List<String[]> oc = await capturadeOC.GetDataOCVisor();
      return Json(new { data = oc });
    }

    public async Task<JsonResult> GetDataLineasVisorAsync(String OC, String itemNumber, String revision, String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      List<String[]> ocLine = await capturadeOC.GetDataOCLineaVisor(OC, itemNumber, revision);
      return Json(new { data = ocLine });
    }

    public async Task<FileResult> ConvertToPDF(String html, String Company)
    {
      PdfTableLinesTransform res = Newtonsoft.Json.JsonConvert.DeserializeObject<PdfTableLinesTransform>(html);
      var arrayCompleto = res.data;
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      String PDF = await capturadeOC.PDFVisor(arrayCompleto);
      byte[] pdfByteArray = Encoding.UTF8.GetBytes(PDF);
      //Console.WriteLine(Encoding.ASCII.GetChars(pdfByteArray));

      var pdfstream = new MemoryStream();

      var w = new StreamWriter(pdfstream);
      w.Write(PDF);
      w.Flush();
      pdfstream.Position = 0;
      HtmlConverter.ConvertToPdf(PDF, pdfstream);
      MemoryStream pdfstream2 = new MemoryStream(pdfstream.ToArray());
      FileResult fileDownload = File(pdfstream2, "application/pdf");
      return fileDownload;

    }

    public IActionResult EnviarPDF(String ocPDF, String revisionPDF, String ocLotePDF, String Company)
    {
      CapturadeOC capturadeOC = new CapturadeOC(Company);
      var result = capturadeOC.SendMail(ocPDF, revisionPDF, ocLotePDF,Company);
      return Json(result);
    }

    public IActionResult SetRevision(String oc)
    {
      Revisiones.SetRevision(oc);
      return Json("Exito");
    }

    public async Task<ActionResult> GetListOCAsync(String Company)
    {
      CapturadeOC capturaOC = new CapturadeOC(Company);
      List<OCList> ListaOc = await capturaOC.getListOC();
      return Json(new { data = ListaOc });
    }

    public async Task<JsonResult> SendMailRecibosAsync(String oc, String revision, String company)
    {
      CapturadeOC captura = new CapturadeOC(company);
      var result = await captura.SendMailRecibos(oc, revision, company);
      return Json(result);
    }
  }
}

Controllers/CedisController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CodigosQRComprasCEDIS_2._0.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CodigosQRComprasCEDIS_2._0.Controllers
{
    public class CedisController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SubrevisionLinea()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> GetDataOCAsync(String OC, String Revision, String Company)
        {
            CapturadeOC capturadeOC = new CapturadeOC(Company);
            ResponseOrdenCompra oc = await capturadeOC.GetDataOC(OC);
            Cedis cedisLine = new Cedis(Company);
            List<String[]> ocLine = await cedisLine.GetDataOCLinea(OC, Revision);
            return Json(new { data = ocLine, dataocHead = (oc.value.Count > 0) ? oc.value[0] : null });
        }

        [HttpPost]
        public async Task<ActionResult> UploadFilesAsync(String purchaseOrderNumber,String revision, String purchaseOrderNumberRev,String Company)
        {
            IFormFileCollection files = Request.Form.Files;
            var fail = false;
            ResultImg result = new ResultImg();
            foreach (IFormFile file in files)
            //for(int i = 0; i < files.Count; i++)  
            {
                Cedis cedisImages = new Cedis(Company);
                result = await cedisImages.uploadFiles(file, purchaseOrderNumber, revision, purchaseOrderNumberRev, User.Identity.Name);
                if (result.estatus == "FailDuplicado")
                {
                    fail = true;
                }
                Thread.Sleep(250);
            }
            if (fail)
            {
                return Ok("Imagen duplicada");
            }
            else
            {
                return Ok(result);
            }
        }

        [HttpPost]
        public async Task<ActionResult> GetServerDocsAsync(String purchaseOrderNumber, String lineNumber, String itemNumber,String Company)
        {
            Cedis cedisImgs = new Cedis(Company);
            var result = await cedisImgs.getServerDocs(purchaseOrderNumber, lineNumber, itemNumber);
            return Ok(new { mockfiles = result });
        }

        [HttpPost]
        public async Task<ActionResult> RemoveFilesAsync(String purchaseOrderNumber, String lineNumber, String itemNumber, int idCodigos,String Company)
        {
            Cedis cedisRemoveImage = new Cedis(Company);
            var result = await cedisRemoveImage.removeFiles(purchaseOrderNumber, lineNumber, itemNumber, idCodigos);
            return Ok(result);
        }

        public async Task<ActionResult> GetListOCAsync(String Company)
        {
            Cedis cedisOC = new Cedis(Company);
            List<OCList> ListaOc = await cedisOC.getListOC();
            return Json(new { data = ListaOc });
        }

        public async Task<JsonResult> SendMailComprasAsync(String oc, String revision,String company)
        {
            Cedis captura = new Cedis(company);
            var result = await captura.SendMailCompras(oc, revision,company);
            return Json(result);
        }

        public async Task<JsonResult> SetSubrevisionAsync(List<SubRevision> subRev, String revision,String Company)
        {
            Cedis cedisSubRev = new Cedis(Company);
            var result = await cedisSubRev.SetSubrevision(subRev,revision);
            return Json(result);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodigosQRComprasCEDIS_2._0</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/sweetalert2.css">
    <link rel="stylesheet" href="~/css/dropzone.css">
    <link rel="stylesheet" href="~/css/selectize.css">
</head>
<body style="overflow:hidden">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3" style="background: rgb(7,128,225); background: linear-gradient(168deg, rgba(7,128,225,1) 35%, rgba(108,20,235,0.7651435574229692) 89%);">
            <div class="row" style="margin-left:0px;margin-right:0px;width:100%">
                <div class="col-md-2">
                    <a class="navbar-brand" asp-area="" asp-controller="CapturadeOC" asp-action="Index">Codigos QR</a>
                </div>
                <div class="col-md-2">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="col-md-8">
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            @if (User.Identity.IsAuthenticated && User.IsInRole("compras"))
                            {
                                String hidden = "";
                                @if (ViewBag.vista == "capturaOC")
                                {
                                    hidden = "";
                                }
                                else
                                {
                                    hidden = "hidden";
                                }
                                <li class="nav-item">
                                    <a href="javascript:showCaptura()" @hidden style="text-decoration:none;"><i class="fa fa-list-alt fa-2x" style="cursor:pointer;color:white;padding-left:15px;padding-right:15px;"></i> <span style="color:white;">Captura de OC</span></a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:showCapturaImgs()" @hidden style="text-decoration:none;"><i class="fa fa-cubes fa-2x" style="cursor:pointer;color:white;padding-left:15px;padding-right:15px;"></i> <span style="color:white;">Captura de Lotes</span></a>
                                </li>
                                <li class="nav-item">
                                    <a style="cursor: pointer;text-decoration:none;" asp-controller="CapturadeOC" asp-action="VisorCodigosQR"><i class="fa fa-table fa-2x" style="cursor:pointer;color:white;padding-left:15px;padding-right:15px;"></i> <span style="color:white;">Resumen de OC</span></a>
                                </li>
                            }
                            else if (User.Identity.IsAuthenticated && User.IsInRole("almacen"))
                            {
                                <li class="nav-item">
                                    <a style="cursor: pointer; text-decoration:none;" asp-controller="Cedis" asp-action="Index"><i class="fa fa-cubes fa-2x" style="cursor:pointer;color:white;padding-left:15px;padding-right:15px;" onclick="showCapturaImgs()"></i> <span style="color:white;">Captura de Lotes</span></a>
                                </li>
                                <li class="nav-item">
                                    <a style="cursor: pointer;text-decoration:none;" asp-controller="CapturadeOC" asp-action="VisorCodigosQR"><i class="fa fa-table fa-2x" style="cursor:pointer;color:white;padding-left:15px;padding-right:15px;"></i> <span style="color:white;">Resumen de OC</span></a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    @if (User.Identity.IsAuthenticated && !User.IsInRole("almacen") && ViewBag.vista == "capturaOC")
    {
    <div class="row" style="bottom: 60px;position: absolute;width: 40%;">
        <div class="col-md-12 oculta" style="position: relative;height: auto;">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link nav-series active" data-toggle="tab" href="#numerosSerie">Numeros de Serie</a>
                </li>
            </ul>
            <div class="tab-content" style="max-height:180px;overflow-y:scroll;overflow-x:hidden;">
                <div class="tab-pane active" id="numerosSerie">
                </div>
            </div>
        </div>
    </div>
    }
    <footer class="border-top footer text-muted" style="z-index:2;background-color:white;">
        <div class="container">
            &copy; 2020 - Avance y Tecnologia en Plásticos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> Fase II
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/capturaDeOC.js" asp-append-version="true"></script>
    <script src="~/js/Cedis.js" asp-append-version="true"></script>
    <script src="~/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.js" asp-append-version="true"></script>
    <script src="~/js/dropzone.js" asp-append-version="true"></script>
    <script src="~/js/selectize.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>